### PR TITLE
Updated to ACF 4 and Composer

### PR DESCRIPTION
**Pull request by xavierpriour**
Hi, rewrote your field to have it work with ACF v4.
Also added a composer.json file to make it compatible with Composer.

### CODE REVIEW

**Comment by xavierpriour** [comment]
@jonathan-dejong could you please tag the repo version as "2.0.0"?
Would make it easier to work with Composer.
Thanks,

**Comment by jonathan-dejong** [comment]
Done

**Comment by xavierpriour** [comment]
Hi Jon,

Thanks but you actually need to create the tags in git itself
(command-line):
  git tag 2.0.0
  git push --tags

Then they will appear in Github "release" tab (
https://github.com/jonathan-dejong/acf-pages-by-template/releases).

And the final part would be to submit the package to packagist (Composer's
package registry):
  https://packagist.org/packages/submit (you can login with your github
account)

That way everyone can use it straight from Composer

Thanks,
Xavier

**Comment by jonathan-dejong** [comment]
Hi Xavier, 

I'm not using composer myself at the moment but since you took the time to update the addon I've created a package and setup the git tag
https://packagist.org/packages/jonathan-dejong/acf-pages-by-template

Altho I don't seem to be able to get the auto updater from github to work properly. What should be the domain value for the webhook?

**Comment by xavierpriour** [comment]
Hi Jon,

Thanks a lot for going through all that for me, everything works great now!
For the webhook domain should be http://packagist.org

On a personal note, if you do still do php dev I highly recommend you try
Composer, it's a blast once setup :)

**Comment by jonathan-dejong** [comment]
No problem, alright I'll give it one more shot then :+1: 

Yes I do php dev daily as it's my job :) These plugins are just stuff I put up as contribution to the community. I'm currently using a workflow with github, vagrant, codekit, sass, compass etc. I should probably check composer out too but sometimes you just gotta take your time and get used to some of the services before adding new ones..

**Pull request merged**
